version: "3.2"
services:
  app:
    container_name: FindBi
    image: vaawel/findbi:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3005:3000

    networks:
      - nginx-proxy-manager
networks:
  nginx-proxy-manager:
    external: true
